### ISSUE TITLE
Laravel 5.5 Support

### ISSUE THREAD

**Issue by nickbryan** [Devitek/laravel-yaml-translation#11]
Hi,

Package needs updating to support Laravel 5.5. The dependencies in composer.json are stopping any update.

There is also a change in Laravel core that will need implementing:

> The LoaderInterface

> The Illuminate\Translation\LoaderInterface interface has been moved to  Illuminate\Contracts\Translation\Loader.

Not sure if there is anything else at the moment.

Cheers

**Comment by nickbryan** [comment]
I have created pull request #12  to fix this, tested on my local.

**Comment by CaporalDead** [comment]
Thanks @nickbryan, you can now use the 4.* branch
