### ISSUE TITLE
not working in Laravel 5.1

### ISSUE THREAD

**Issue by unitedworx** [Devitek/laravel-yaml-translation#4]
have you tried this with Laravel 5.1?? 

It seems to break laravel when laravel-yaml-translation is enabled. once i disable this package my setup works fine. Tried to update the package but i get the same error whatever i change. FatalErrorException in ClassLoader.php line 314: Maximum function nesting level of '100' reached, aborting!

**Comment by CaporalDead** [comment]
Nope, didn't have the time to synchronize this repo :/. I'll check it asap !

**Comment by unitedworx** [comment]
No worries , tool only 30 min to figure it out and update it for laravel 5.1 

Check my pull request
https://github.com/Devitek/laravel-yaml-translation/pull/5
