### ISSUE TITLE
Infinite nesting

### ISSUE THREAD

**Issue by finalgamer** [Devitek/laravel-yaml-translation#9]
I am used to the Symfony YAML translations where nesting is possible infinitly.
Implementing that here would only require to add an

```php 
\Illuminate\Support\Arr::dot()
```
after parsing the YAML file.

Would this be possible to implement?

**Comment by CaporalDead** [comment]
Hi @finalgamer, I'll try to add this today or, if you want, you can submit a PR. Keep me up to date.

**Comment by finalgamer** [comment]
I've created a PR #10 I also implemented the feature for the php translations
